### PR TITLE
Follow googlecartographer/cartographer_ros/#683

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Adds the publish_frame_projected_to_2d option.

### CODE REVIEW

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Refusing to merge, since the combined checks state is failure

**Comment by MichaelGrupp** [comment]
should work now that the PR in cartographer_ros is merged

**Comment by gaschler** [comment]
@wally-the-cartographer merge

**Comment by wally-the-cartographer** [comment]
Merge requested by authorized user gaschler. Merge queue now has a length of 1.

**Pull request merged**
